#don't touch this
version: 6

# When you installed a new update, (if true) the plugin will try to add all the missing config values. This applies to Commands.yml, Lang.yml and Config.yml
# This WILL remove all comments made and the file might be harder to read.
auto-update-config: false

# only works when forms are enabled
enable-categories: true

# the default values for the kit flags when creating a kit
default-flags:
  locked: true
  emptyOnClaim: false
  doOverride: false
  doOverrideArmor: false
  alwaysClaim: false
  chestKit: false

# this will only change /kit, not /createkit or /deletekit
use-forms: true

# show players kits they don't have permission to claim
show-locked: false
# show players categories they don't have permission to see
show-locked-categories: false

# if true, the player also needs the easykits.kit.<kitname> permission to equip the chestkit.
chestKit-locked: false

chestKit-itemid: 54

# give all EasyKits.kit.* permissions to operators
op-has-all-kits: true
# give all EasyKits.free.* permissions to operators
op-has-free-kits: false
# give all EasyKits.instant.* permissions to operators
op-has-instant-kits: false
# give all EasyKits.category.* permissions to operators
op-has-all-categories: true

# item format
#
# enter nbt for a format that saves items exactly, with all their NBT tags. This comes with the disadvantage of not being able to easily edit this from the config files. It should work with all custom enchant plugins, banknotes, storing chestkits in kits ...
# enter simple for a format that only saves certain info. This format will be incompatible with some plugins like customenchants (excluding PiggyCustomEnchants).
#
item-format: "nbt"

# economy stuff

# for if you're using multieconomy
multieconomy-currency: "dollars"