#don't touch this
version: 3

# the default values for the kit flags when creating a kit
default-flags:
  locked: true
  emptyOnClaim: false
  doOverride: false
  doOverrideArmor: false
  alwaysClaim: false
  chestKit: false

# this will only change /kit, not /createkit or /deletekit
use-forms: true

# show players kits they don't have permission to claim
show-locked: false

# if true, the player also needs the easykits.kit.<kitname> permission to equip the chestkit.
chestKit-locked: false

chestKit-itemid: 54

# give all EasyKits.kit.* permissions to operators
op-has-all-kits: true
# give all EasyKits.free.* permissions to operators
op-has-free-kits: false
# give all EasyKits.instant.* permissions to operators
op-has-instant-kits: false

# economy stuff

# for if you're using multieconomy
multieconomy-currency: "dollars"